'use client';

import { useEffect, useState } from 'react';
import { createClient } from '@/utils/supabase/client';

export default function PriporociFlow({ base = '' }: { base?: string }) {
  const jeEn = base === '/en'; const L = (sl: string, en: string) => jeEn ? en : sl;
  const [povezava, setPovezava] = useState(''); const [stevilo, setStevilo] = useState(0); const [kopirano, setKopirano] = useState(false); const [skrito, setSkrito] = useState(true);
  useEffect(() => { setSkrito(localStorage.getItem('pinart-flow-podpora-skrita') === '1'); void (async () => { const supabase = createClient(); const { data: auth } = await supabase.auth.getUser(); const user = auth.user; if (!user) return; let { data: koda } = await supabase.from('referral_codes').select('id,code').eq('owner_user_id', user.id).maybeSingle(); if (!koda) { const code = crypto.randomUUID().replace(/-/g, '').slice(0, 16); const odgovor = await supabase.from('referral_codes').insert({ owner_user_id: user.id, code }).select('id,code').single(); koda = odgovor.data; } if (!koda) return; setPovezava(`${window.location.origin}${base}/kalkulator/prijava?nov=1&ref=${koda.code}`); const { count } = await supabase.from('referral_registrations').select('id', { count: 'exact', head: true }).eq('code_id', koda.id); setStevilo(count || 0); })(); }, [base]);
  return <>{<section style={{ padding: '1.2rem', border: '1px solid rgba(17,17,17,.12)', borderRadius: '1rem', background: 'rgba(255,255,255,.55)' }}><h2>{L('Priporoči Flow', 'Recommend Flow')}</h2><p style={{ color: '#6b655d' }}>{L('Deli svojo povezavo. Registracije in prihodnja nagrada se zabeležijo samodejno.', 'Share your link. Registrations and the future reward are recorded automatically.')}</p>{povezava ? <div style={{ display: 'flex', gap: '.5rem', flexWrap: 'wrap' }}><input readOnly value={povezava} aria-label={L('Tvoja priporočilna povezava', 'Your referral link')} style={{ flex: '1 1 18rem', minWidth: 0 }} /><button type="button" onClick={async () => { await navigator.clipboard.writeText(povezava); setKopirano(true); }}>{kopirano ? L('Kopirano', 'Copied') : L('Kopiraj povezavo', 'Copy link')}</button></div> : <p>{L('Pripravljam povezavo …', 'Preparing link …')}</p>}<small style={{ color: '#6b655d' }}>{L(`Registracij prek povezave: ${stevilo}`, `Registrations via your link: ${stevilo}`)}</small></section>}{!skrito && <aside style={{ marginTop: '1rem', padding: '.8rem 1rem', display: 'flex', gap: '.7rem', alignItems: 'center', borderTop: '1px solid rgba(17,17,17,.12)', color: '#6b655d' }}><span style={{ flex: 1 }}>{L('Flow ti prihrani čas? Podpri razvoj.', 'Does Flow save you time? Support its development.')}</span><a href="mailto:tina@pinart.si?subject=Podpora%20razvoju%20Flowa">{L('Podpri razvoj', 'Support development')}</a><button type="button" aria-label={L('Skrij povabilo za podporo', 'Hide support invitation')} onClick={() => { localStorage.setItem('pinart-flow-podpora-skrita', '1'); setSkrito(true); }}>×</button></aside>}</>;
}
