export type PricingService = { id: string; ime: string; osnova: number };

export const PRICING_SERVICES: PricingService[] = [
  { id: 'logo', ime: 'Logotip + osnovna identiteta', osnova: 650 },
  { id: 'cgp', ime: 'Celostna grafična podoba', osnova: 1350 },
  { id: 'web', ime: 'Spletna stran', osnova: 1400 },
  { id: 'kampanja', ime: 'Kampanja / oglasni vizuali', osnova: 900 },
  { id: 'publikacija', ime: 'Publikacija / tiskovina', osnova: 700 },
  { id: 'embalaza', ime: 'Embalaža / produkt', osnova: 900 },
  { id: 'ilustracija', ime: 'Ilustracija / vizualni svet', osnova: 550 },
  { id: 'direkcija', ime: 'Kreativna direkcija', osnova: 900 },
  { id: 'fotografija', ime: 'Fotografiranje', osnova: 450 },
  { id: 'copy', ime: 'Besedila / copywriting', osnova: 450 },
  { id: 'interier', ime: 'Interier dizajn', osnova: 1200 },
  { id: 'arhitektura', ime: 'Arhitekturno oblikovanje', osnova: 2200 },
  { id: 'razstava', ime: 'Razstavni / scenski dizajn', osnova: 1300 },
  { id: 'produktni', ime: 'Produktni / pohištveni dizajn', osnova: 1600 },
  { id: 'uxui', ime: 'UX/UI dizajn', osnova: 1100 },
  { id: 'aplikacija', ime: 'Mobilna aplikacija', osnova: 2400 },
  { id: 'dizajnsistem', ime: 'Dizajn sistem', osnova: 1600 },
  { id: 'smm', ime: 'Social media vodenje', osnova: 650 },
  { id: 'seo', ime: 'SEO', osnova: 550 },
  { id: 'email', ime: 'Email marketing', osnova: 350 },
  { id: 'pr', ime: 'PR / odnosi z javnostmi', osnova: 750 },
  { id: 'video', ime: 'Video produkcija', osnova: 1300 },
  { id: 'motion', ime: 'Motion / animacija', osnova: 750 },
  { id: 'render3d', ime: '3D vizualizacije', osnova: 650 },
  { id: 'strategija', ime: 'Brand strategija', osnova: 1100 },
];
